train:
  learning_rate: 0.001
  lstm_1_units: 100
  lstm_2_units: 50
  lstm_3_units: 50
  lstm_4_units: 50
  dropout_rate: 0.3
  epochs: 100
  batch_size: 32
  random_seed: 42

preprocess_data:
  test_size: 0.25
  random_seed: 42
